name: pokebook
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  fast_immutable_collections: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_gen_runner: ^5.4.0
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  freezed: ^2.4.7
  hive: ^2.2.3
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/src/core/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Sofia_Sans
      fonts:
        - asset: assets/fonts/Sofia_Sans/SofiaSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sofia_Sans/SofiaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sofia_Sans/SofiaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Sofia_Sans/SofiaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sofia_Sans/SofiaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sofia_Sans/SofiaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sofia_Sans/SofiaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sofia_Sans/SofiaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Sofia_Sans/SofiaSans-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
